# Generated by Django 6.1.1 on 2026-09-28 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição no cardápio')),
            ],
            options={
                'verbose_name_plural': 'Categorias',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(max_length=100)),
                ('cliente_telefone', models.CharField(help_text='WhatsApp do cliente', max_length=20)),
                ('endereco_entrega', models.TextField(help_text='Rua, número, bairro e complemento')),
                ('ponto_referencia', models.CharField(blank=True, max_length=150)),
                ('forma_pagamento', models.CharField(choices=[('DINHEIRO', 'Dinheiro na Entrega'), ('CARTAO', 'Cartão na Entrega'), ('PIX', 'Pix na Entrega')], default='PIX', max_length=20)),
                ('troco_para', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('RECEBIDO', 'Recebido'), ('PREPARO', 'Em Preparo'), ('ENTREGA', 'Saiu para Entrega'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='RECEBIDO', max_length=20)),
                ('observacoes', models.TextField(blank=True, help_text='Ex: tirar cebola, maionese à parte')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, help_text='Ingredientes e detalhes')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('disponivel', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='delivery.categoria')),
            ],
            options={
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='delivery.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delivery.produto')),
            ],
            options={
                'verbose_name_plural': 'Itens dos Pedidos',
            },
        ),
    ]
